# Generated by Django 4.2.27 on 2026-01-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelentry',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='longitude',
        ),
    ]
