# Generated by Django 4.2.27 on 2026-01-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_travelentry_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelentry',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
